### ISSUE TITLE
Ignore LLAPITransport.cs

### ISSUE THREAD

**Issue by MrGadget1024** [Lymdun/MirrorConverter#10]
When your doing script conversion, make sure you ignore 
Assets/Mirror/Runtime/Transport/LLAPITransport.cs

That one needs to retain these usings:
```
using System;
using UnityEngine;
using UnityEngine.Networking;
using UnityEngine.Networking.Types;
```

**Comment by Lymdun** [comment]
Need to be tested, but the converter isn't supposed to modify any Mirror file, so it shouldn't be a problem

**Comment by MrGadget1024** [comment]
I had someone in Discord who showed me their LLAPITransport.cs was modified by running the tool.

**Comment by Lymdun** [comment]
With the latest update?

**Comment by MrGadget1024** [comment]
Yes last night he cloned your repo and ran it and said those errors came up.

**Comment by MrGadget1024** [comment]
It is possible he inadvertently changed them on his own trying to do a conversion by hand before he ran the tool.  I'm just going from what he said happened.  If you can't reproduce, then close.

**Comment by MrGadget1024** [comment]
I ran the converter again with Rucksack and it left LLAPITransport alone.
I think this was user error.
