### ISSUE TITLE
NRE converting prefabs

### ISSUE THREAD

**Issue by MrGadget1024** [Lymdun/MirrorConverter#13]
```
NullReferenceException: Object reference not set to an instance of an object
Mirror.MigrationUtilities.Utils.CopyProperties (System.Object source, System.Object destination) (at Assets/Mirror/Migration/Editor/Utils.cs:65)
Mirror.MigrationUtilities.Utils.ReplaceNetworkComponent[TSource,TDestination] (UnityEngine.GameObject prefab) (at Assets/Mirror/Migration/Editor/Utils.cs:24)
Mirror.MigrationUtilities.Components.ReplaceEveryNetworkIdentity (UnityEngine.GameObject go) (at Assets/Mirror/Migration/Editor/Components.cs:156)
Mirror.MigrationUtilities.Components.FindAndReplaceUnetComponents (System.Int32& netComponentObsolete) (at Assets/Mirror/Migration/Editor/Components.cs:70)
UnityEngine.Debug:LogException(Exception)
Mirror.MigrationUtilities.Components:FindAndReplaceUnetComponents(Int32&) (at Assets/Mirror/Migration/Editor/Components.cs:92)
Windows:ReplaceComponentsOnPrefabs() (at Assets/Mirror/Migration/Editor/Windows.cs:14)
```

**Comment by Lymdun** [comment]
Which Unity version?
Do you knwow what prefab caused it?

**Comment by MrGadget1024** [comment]
2018.3.6 and no, I don't know which prefab.  I'll need to find where to stick some debug logging.

**Comment by MrGadget1024** [comment]
[Editor - Copy.log](https://github.com/Lymdun/MirrorConverter/files/2924416/Editor.-.Copy.log)
see if this helps

**Comment by MrGadget1024** [comment]
This has the log and the prefab and meta file

[Editor - Copy.zip](https://github.com/Lymdun/MirrorConverter/files/2924421/Editor.-.Copy.zip)

**Comment by MrGadget1024** [comment]
Can you make the tool build a list of prefabs it choked on, and continue past them to do the rest, and then write one log entry with that list so people can hand fix that one or those few?  I had another person today hit this same issue.

**Comment by Lymdun** [comment]
https://github.com/Lymdun/MirrorConverter/commit/9e5cedb345e2278b03528361161b660a2eee2d29 should fix it

**Comment by MrGadget1024** [comment]
Fixed
