### ISSUE TITLE
NetworkClient Is Static

### ISSUE THREAD

**Issue by MrGadget1024** [Lymdun/MirrorConverter#20]
NetworkClient is static now, so you can do these replacements:

Replace `NetworkManager.singleton.client` with `NetworkClient`
Replace `NetworkClient.allClients[0]` with `NetworkClient`

**Comment by Lymdun** [comment]
https://github.com/Lymdun/MirrorConverter/commit/3b0b8de6d66a0f1ee47c61eacc305a929acdb5e0
