### ISSUE TITLE
SetChannelOption not fixed in conversion

### ISSUE THREAD

**Issue by MrGadget1024** [Lymdun/MirrorConverter#9]
Two errors result of converting scripts:
```
'NetworkConnection' does not contain a definition for 'SetChannelOption' and no accessible extension method 'SetChannelOption' accepting a first argument of type 'NetworkConnection' could be found (are you missing a using directive or an assembly reference?)
```
```
The name 'ChannelOption' does not exist in the current context
```

Original line:
```
conn.SetChannelOption(Channels.DefaultReliable, ChannelOption.MaxPendingBuffers, 500);
```

In this case the line can simply be commented out since it's not applicable to Telepathy and would be different in any other transport.

**Comment by MrGadget1024** [comment]
Can you comment out lines that have `.SetChannelOption` in them?

**Comment by Lymdun** [comment]
https://github.com/Lymdun/MirrorConverter/commit/5501e44818d53943c3638ec8f120b85a4e880f21
